<div id="hello-world" data-bind="scope: 'hello' "><!-- ko template: getTemplate() --><!-- /ko --></div><script type="text/x-magento-init">
    {
        "#hello-world":{
            "Magento_Ui/js/core/app": {
                "components": {
                    "hello": {
                        "template": "Magento_Theme/helloo"
                    }
                }
        }
        }
    }</script>