<style>
    .content_detail li {
        color: var(--body-default, #282828);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 500;
        line-height: 20px;
        letter-spacing: 0.7px;
    }
</style>
<div class="detail_description_product mt-3">
    <ul class="content_detail">
        <li>Direct pouring head</li>
        <li>Stainless steel filter</li>
        <li>Wattage: 130W</li>
        <li>Anti-dripping</li>
        <li>Anti-slipping base</li>
    </ul>
</div>