<style>
    .title-deal{
        color: var(--primary-500, #93117B);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 700;
        line-height: 20px; 
        letter-spacing: 0.7px;
    }
    .info-content{
        color: var(--body-default, #282828);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 700;
        line-height: 20px;
        letter-spacing: 0.7px;
    }
    .price {
        color: var(--body-default, #282828);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 500;
        line-height: 20px; /* 142.857% */
        letter-spacing: 0.7px;
        text-decoration-line: line-through;
    }
    .cost{
        display: flex;
    }

    .cost span{
        color: #ffff;
        margin-left: 10px;
        background-color: rgba(242, 53, 27, 1);
    }
    .infor{
        color: var(--body-default, #282828);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 700;
        line-height: 20px;
        letter-spacing: 0.7px;
    }
    
</style>
<div class="container">
    <div class="row mt-5">
            <h1>Deals Of The Day </h1>
            <hr class="mt-3">
            <div class="row">
                <div class="col-12">
                    <div class="carousel-deal-of-day">
                            <div class="item" style="display: flex; align-items: center;">
                                <div style="width: 200px; height: 200px;">
                                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/deal.png'); ?>" alt="" style="max-width: 100%; width:100%;" />
                                    <div>
                                        <h4 style=" display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; text-overflow: ellipsis; color: #93117B; margin-top: 1rem; margin-bottom: 0px;">Sữa Dưỡng Phục Hồi Tái Tạo Da B5 Neogence 50</h4>
                                        <p class="productslider mt-2"></p>
                                        <p class="price">799.000 đ</p>
                                        <p class="infor" style="font-weight: bold;">
                                                <svg style="color: #93117B;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                                </svg> 
                                            Member Wednesday
                                        </p>
                                        <p class="infor" style="font-weight: bold;"> 
                                                <svg style="color: #93117B;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightning-charge-fill" viewBox="0 0 16 16">
                                                    <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
                                                </svg>  
                                            From 00:00 to 15:00
                                        </p>
                                        <h4 class="cost" style="color: red;">355.000 đ <span><p>-50%</p></span></h4>
                                    </div>
                                </div>
                            </div>

                            <div class="item" style="display: flex; align-items: center;">
                                <div style="width: 200px; height: 200px;">
                                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/deal.png'); ?>" alt="" style="max-width: 100%; height: auto;" />
                                    <div>
                                        <h4 style=" display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; text-overflow: ellipsis; color: #93117B; margin-top: 1rem; margin-bottom: 0px;">Sữa Dưỡng Phục Hồi Tái Tạo Da B5 Neogence 50</h4>
                                        <p class="productslider mt-2"></p>
                                        <p class="price">799.000 đ</p>
                                        <p class="infor" style="font-weight: bold;">
                                                <svg style="color: #93117B;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                                </svg> 
                                            Member Wednesday
                                        </p>
                                        <p class="infor" style="font-weight: bold;"> 
                                                <svg style="color: #93117B;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightning-charge-fill" viewBox="0 0 16 16">
                                                    <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
                                                </svg>  
                                            From 00:00 to 15:00
                                        </p>
                                        <h4 class="cost" style="color: red;">355.000 đ <span><p>-50%</p></span></h4>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="item" style="display: flex; align-items: center;">
                                <div style="width: 200px; height: 200px;">
                                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/deal.png'); ?>" alt="" style="max-width: 100%; height: auto;" />
                                    <div>
                                        <h4 style=" display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; text-overflow: ellipsis; color: #93117B; margin-top: 1rem; margin-bottom: 0px;">Sữa Dưỡng Phục Hồi Tái Tạo Da B5 Neogence 50</h4>
                                        <p class="productslider mt-2"></p>
                                        <p class="price">799.000 đ</p>
                                        <p class="infor" style="font-weight: bold;">
                                                <svg style="color: #93117B;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                                </svg> 
                                            Member Wednesday
                                        </p>
                                        <p class="infor" style="font-weight: bold;"> 
                                                <svg style="color: #93117B;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightning-charge-fill" viewBox="0 0 16 16">
                                                    <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
                                                </svg>  
                                            From 00:00 to 15:00
                                        </p>
                                        <h4 class="cost" style="color: red;">355.000 đ <span><p>-50%</p></span></h4>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="item" style="display: flex; align-items: center;">
                                <div style="width: 200px; height: 200px;">
                                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/deal.png'); ?>" alt="" style="max-width: 100%; height: auto;" />
                                    <div>
                                        <h4 style=" display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; text-overflow: ellipsis; color: #93117B; margin-top: 1rem; margin-bottom: 0px;">Sữa Dưỡng Phục Hồi Tái Tạo Da B5 Neogence 50</h4>
                                        <p class="productslider mt-2"></p>
                                        <p class="price">799.000 đ</p>
                                        <p class="infor" style="font-weight: bold;">
                                                <svg style="color: #93117B;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                                </svg> 
                                            Member Wednesday
                                        </p>
                                        <p class="infor" style="font-weight: bold;"> 
                                                <svg style="color: #93117B;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightning-charge-fill" viewBox="0 0 16 16">
                                                    <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
                                                </svg>  
                                            From 00:00 to 15:00
                                        </p>
                                        <h4 class="cost" style="color: red;">355.000 đ <span><p>-50%</p></span></h4>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="item" style="display: flex; align-items: center;">
                                <div style="width: 200px; height: 200px;">
                                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/deal.png'); ?>" alt="" style="max-width: 100%; height: auto;" />
                                    <div>
                                        <h4 style=" display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; text-overflow: ellipsis; color: #93117B; margin-top: 1rem; margin-bottom: 0px;">Sữa Dưỡng Phục Hồi Tái Tạo Da B5 Neogence 50</h4>
                                        <p class="productslider mt-2"></p>
                                        <p class="price">799.000 đ</p>
                                        <p class="infor" style="font-weight: bold;">
                                                <svg style="color: #93117B;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                                </svg> 
                                            Member Wednesday
                                        </p>
                                        <p class="infor" style="font-weight: bold;"> 
                                                <svg style="color: #93117B;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightning-charge-fill" viewBox="0 0 16 16">
                                                    <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
                                                </svg>  
                                            From 00:00 to 15:00
                                        </p>
                                        <h4 class="cost" style="color: red;">355.000 đ <span><p>-50%</p></span></h4>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="item" style="display: flex; align-items: center;">
                                <div style="width: 200px; height: 200px;">
                                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/deal.png'); ?>" alt="" style="max-width: 100%; height: auto;" />
                                    <div>
                                        <h4 style=" display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; text-overflow: ellipsis; color: #93117B; margin-top: 1rem; margin-bottom: 0px;">Sữa Dưỡng Phục Hồi Tái Tạo Da B5 Neogence 50</h4>
                                        <p class="productslider mt-2"></p>
                                        <p class="price">799.000 đ</p>
                                        <p class="infor" style="font-weight: bold;">
                                                <svg style="color: #93117B;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                                    <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                                                    <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                                                </svg> 
                                            Member Wednesday
                                        </p>
                                        <p class="infor" style="font-weight: bold;"> 
                                                <svg style="color: #93117B;" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-lightning-charge-fill" viewBox="0 0 16 16">
                                                    <path d="M11.251.068a.5.5 0 0 1 .227.58L9.677 6.5H13a.5.5 0 0 1 .364.843l-8 8.5a.5.5 0 0 1-.842-.49L6.323 9.5H3a.5.5 0 0 1-.364-.843l8-8.5a.5.5 0 0 1 .615-.09z"/>
                                                </svg>  
                                            From 00:00 to 15:00
                                        </p>
                                        <h4 class="cost" style="color: red;">355.000 đ <span><p>-50%</p></span></h4>
                                    </div>
                                </div>
                            </div>
                            

                            
                        
                    </div>
                </div>
            </div>
     </div>
</div>