<div class="container">
    <div class="row">
        <div class="col-8">
                    <div class="carousel-slider">
                        <div class="item">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Slider.png'); ?>" alt="Chưa có ảnh" />
                        </div>
                        <div class="item">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Slider.png'); ?>" alt="Chưa có ảnh" />
                        </div>
                        <div class="item">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Slider.png'); ?>" alt="Chưa có ảnh" />
                        </div>
                    </div>
              </div>

        <div class="col-4">
            <img class="mb-3" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Artboard.png'); ?>" alt="Chưa có ảnh" />
            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/banner-facema_sk.png'); ?>" alt="Chưa có ảnh" />
        </div>
    </div>
</div>
