<style>
    .title-deal{
        color: var(--primary-500, #93117B);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 700;
        line-height: 20px; 
        letter-spacing: 0.7px;
    }
    .info-content{
        color: var(--body-default, #282828);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 700;
        line-height: 20px;
        letter-spacing: 0.7px;
    }
    .price {
        color: var(--body-default, #282828);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 500;
        line-height: 20px; /* 142.857% */
        letter-spacing: 0.7px;
        text-decoration-line: line-through;
    }
    .cost{
        display: flex;
    }

    .cost span{
        color: #ffff;
        margin-left: 10px;
        background-color: rgba(242, 53, 27, 1);
    }
    .infor{
        color: var(--body-default, #282828);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 700;
        line-height: 20px;
        letter-spacing: 0.7px;
    }
    
</style>
<div class="container">
    <div class="row mt-5">
            <h1><?= __('Deals Of The Day') ?> </h1>
            <hr class="mt-3">
            <div class="row">
                <div class="col-12" id="product-list-container" data-bind="scope: 'product-list'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
            </div>
     </div>
</div>

<script type="text/x-magento-init">
{
    "#product-list-container": {
        "Magento_Ui/js/core/app": {
            "components": {
                "product-list": {
                    "component": "Magento_Theme/js/custom-component",
                    "template" : "Magento_Theme/dealofday"
                }
            }
        }
    }
}
</script>